version: "3.4"

x-testdeck:
  service_base: rdtest-generic

services:
  postgres:
    image: postgres
    expose:
      - 5432
    environment:
      POSTGRES_DB: rundeck
      POSTGRES_USER: rundeck
      POSTGRES_PASSWORD: rundeck
  rundeck1:
    links:
      - postgres
    environment:
      CONFIG_SCRIPT_PRESTART: scripts/config-db.sh
      DATABASE_DRIVER: org.postgresql.Driver
      DATABASE_URL: jdbc:postgresql://postgres/rundeck
      DATABASE_USER: rundeck
      DATABASE_PASS: rundeck